# Generated by Django 4.1 on 2022-09-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenceid', models.TextField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Dateofbirth', models.IntegerField()),
                ('Bloodgroup', models.TextField(max_length=100)),
                ('vehicle', models.TextField(max_length=100)),
                ('Fines', models.TextField(max_length=100)),
            ],
        ),
    ]
