# Generated by Django 4.1 on 2022-09-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0004_delete_drivinglicence_delete_licence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='drivinglicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Licenceid', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=10)),
                ('Bloodgroup', models.CharField(max_length=10)),
                ('Dob', models.CharField(max_length=100)),
                ('validfrom', models.CharField(max_length=100)),
                ('validto', models.CharField(max_length=100)),
                ('vehicleclass', models.CharField(max_length=100)),
            ],
        ),
    ]
