# Generated by Django 4.1 on 2022-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0005_drivinglicence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicence',
            name='Address',
            field=models.CharField(max_length=100),
        ),
    ]
