# Generated by Django 4.1 on 2022-10-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0006_alter_drivinglicence_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Licenceid', models.CharField(max_length=100)),
                ('fines', models.CharField(max_length=100)),
            ],
        ),
    ]
