# Generated by Django 4.1 on 2022-10-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0007_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='fines',
            field=models.CharField(max_length=200),
        ),
    ]
