# Generated by Django 4.1 on 2022-10-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0008_alter_fine_fines'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiclefine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleid', models.CharField(max_length=100)),
                ('fines1', models.CharField(max_length=200)),
                ('fines2', models.CharField(max_length=200)),
                ('fines3', models.CharField(max_length=200)),
            ],
        ),
    ]
