# Generated by Django 4.1 on 2022-10-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0009_vehiclefine'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='date',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
