# Generated by Django 4.1 on 2022-10-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0010_fine_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicledetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=200)),
                ('CHASSISNO', models.CharField(max_length=200)),
                ('ENGINENO', models.CharField(max_length=200)),
                ('MAKERNAME', models.CharField(max_length=100)),
                ('MODELNAME', models.CharField(max_length=200)),
                ('MODELDESC', models.CharField(max_length=200)),
                ('REGISTRATIONDATE', models.CharField(max_length=200)),
                ('TAXVALIDUPTO', models.CharField(max_length=100)),
                ('PUCCNO', models.CharField(max_length=200)),
                ('PUCCVALIDUPTO', models.CharField(max_length=200)),
                ('FUELTYPE', models.CharField(max_length=200)),
                ('COLOR', models.CharField(max_length=100)),
                ('SEATCAPACITY', models.CharField(max_length=200)),
                ('INSURANCEPOLICYNO', models.CharField(max_length=200)),
                ('INSURANCEVALIDUPTO', models.CharField(max_length=200)),
                ('FITNESSVALIDUPTO', models.CharField(max_length=200)),
                ('REGISTERINGAUTHORITY', models.CharField(max_length=200)),
            ],
        ),
    ]
