# Generated by Django 4.1 on 2022-10-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0012_vehicledetails_registrationno'),
    ]

    operations = [
        migrations.AddField(
            model_name='fine',
            name='location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fine',
            name='status',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
