# Generated by Django 4.1 on 2022-10-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0014_vehicledetails_rcstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='regfine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REGISTRATIONON', models.CharField(max_length=100)),
                ('fines', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
