# Generated by Django 4.1 on 2022-10-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0015_regfine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regfine',
            old_name='REGISTRATIONON',
            new_name='REGISTRATIONNO',
        ),
    ]
