# Generated by Django 4.1 on 2022-10-07 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0016_rename_registrationon_regfine_registrationno'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetails',
            name='img',
            field=models.ImageField(default='default', upload_to='images'),
            preserve_default=False,
        ),
    ]
