# Generated by Django 4.1 on 2023-06-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0020_phone_delete_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alterationfine',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
