# Generated by Django 4.1 on 2023-06-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvaapp', '0024_alter_alterationfine_registrationno_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phone',
            new_name='status',
        ),
    ]
